### ISSUE TITLE
Failing to package vsix file using vsce

### ISSUE THREAD

**Issue by timsueberkrueb** [meraymond2/idris-vscode#10]
Hey, first of all, thank you for this great extension.
It works perfectly for me when running in extension debug mode via VSCode.
However, when trying to create a `.vsix` file for local installation using `vsce`, the resulting file is incomplete:

```bash
vsce package
```

Contents of the resulting `idris-vscode-0.0.4.vsix`:

* `extension.vsixmanifest`
* `[Content_Types].xml`

If I manually bundle the required files (also tested with webpack) and install the resulting zip/vsix file, it works.

It's perfectly possible that I'm missing something or that the project is not setup yet for bundling or that my local setup is broken. Any pointers would be highly appreciated.

**Comment by dustypomerleau** [comment]
`vsce` should definitely generate an `extension/` directory containing all the goodies. Local setup is a likely culprit. When I run `vsce package` on the current repo, I get the following contents:

```
~/Desktop/idris-vscode-0.0.4
├── [Content_Types].xml
├── extension
│   ├── CHANGELOG.md
│   ├── LICENSE.txt
│   ├── README.md
│   ├── idris-vscode.code-workspace
│   ├── language-configuration.json
│   ├── node_modules
│   ├── out
│   ├── package.json
│   └── syntaxes
└── extension.vsixmanifest
```

My setup:

macOS 10.15.7
VS Code 1.49.2
Node 14.12.0
vsce 1.80.0

**Comment by timsueberkrueb** [comment]
Thank you! It appears like the `node` snap package I was using is at fault. I just replaced that with a deb-based node installation and it works. Sorry for the noise - I will report the (likely) snap-related issue.

```bash
Executing prepublish script 'npm run vscode:prepublish'...
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/3082/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> idris-vscode@0.0.4 vscode:prepublish /home/tim/Dev/GitHub/meraymond2/idris-vscode
> npm run compile

npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/3082/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> idris-vscode@0.0.4 compile /home/tim/Dev/GitHub/meraymond2/idris-vscode
> tsc -p ./

 DONE  Packaged: /home/tim/Dev/GitHub/meraymond2/idris-vscode/idris-vscode-0.0.4.vsix (2 files, 1.04KB)
```

Did not work with `node` snap versions `14.12.0 (3082)` and `12.18.4 (3041)` on Ubuntu 20.04 with vsce `1.80.0`, `code` snap `1.49.2` (45).
Did work with `node` version `v14.12.0` from deb.nodesource.com.
