### ISSUE TITLE
`[] and `() break syntax highlighting

### ISSUE THREAD

**Issue by michaelmesser** [meraymond2/idris-vscode#13]
\`[] and \`() break syntax highlighting. Everything after the \` is the same color till the next \`.

**Comment by meraymond2** [comment]
I think I've fixed this, but it's not a syntactical element I've ever used before, so if you have any example code, that would be useful to confirm. I could only find one file in the Idris2 repo that used this.

Before:
![2020-12-05-183759_1920x1080_scrot](https://user-images.githubusercontent.com/13559686/101260726-b4b6d580-3729-11eb-8558-486ee608ba76.png)
After:
![2020-12-05-183821_1920x1080_scrot](https://user-images.githubusercontent.com/13559686/101260727-b7b1c600-3729-11eb-97f5-877eb04eeea8.png)

**Comment by michaelmesser** [comment]
That looks right to me. \`() contains an expression. \`[] contains declarations.

**Comment by meraymond2** [comment]
This should be fixed in the latest version. Feel free to reopen this if you come across any other cases. :+1:
