### ISSUE TITLE
Show type of hole on hover

### ISSUE THREAD

**Issue by michaelmesser** [meraymond2/idris-vscode#22]
This requires stripping the leading `?`.

https://github.com/edwinb/idris2-vim/blob/964cebee493c85f75796e4f4e6bbb4ac54e2da9e/ftplugin/idris2.vim#L27-L29

**Comment by meraymond2** [comment]
Cool, that's an easy fix :+1: 

Do you prefer having the premises as well in the hover text, or just the type of the hole itself? 
For 
```
imap : Vect n a -> Vect n b
imap xs = ?imap_rhs
```
the full type information it returns 
```
 0 b : Type
 0 a : Type
 0 n : Nat
   xs : Vect n a
-------------------------------------
imap_rhs : Vect n b
```
but that might get annoying if there's a lot of locals.

**Comment by michaelmesser** [comment]
I think it would be best to show the locals at least until you can hover over the locals to see the types.

**Comment by meraymond2** [comment]
This should work now in the latest release.

**Comment by michaelmesser** [comment]
I can confirm that it works.
