### ISSUE TITLE
Idris 2 0.3.0 support

### ISSUE THREAD

**Issue by meraymond2** [meraymond2/idris-vscode#32]
0.3.0 has just been released, so this issue is a reminder to check what's changed and make sure nothing is broken.

**Comment by meraymond2** [comment]
I'm not currently able to run Idris2 0.3.0 with `idris2 --ide-mode`. I'm getting `Uncaught error: (implicit):1:1--1:1:Prelude not found`. There was one failed make test during compilation, so I might try rebuilding it. In the meantime, is anyone else able to run it?

**Comment by zenntenn** [comment]
It's working for me, on Windows 10, compiled in MSYS2.

When I do `idris2 --ide-mode` I get `000018(:protocol-version 2 0)`

**Comment by meraymond2** [comment]
My Prelude bug was unrelated to the new version, it's something to do with the linker paths, which I solved by just compiling it with Nix. The latest is version is out on the unstable channel. 

It doesn't look like much has changed in the new release related to the IDE protocol. The only difference my units tests turned up is in the :metavariables response. Premise names previously had 3 empty spaces in front of them for some reason, now they have 2 empty spaces. That doesn't even affect anything, because I apparently still haven't gotten around to adding the premises to the List Metavariables command.
