### ISSUE TITLE
Is it published to vscode marketplace?

### ISSUE THREAD

**Issue by stereobooster** [meraymond2/idris-vscode#34]
It seems it isn't published to marketplace or miss something?

Want to use it with vcode dev container https://github.com/stereobooster/idris-vscode-remote-development-template

**Comment by zenntenn** [comment]
I'm seeing meraymond.idris-vscode. I don't know how to link to it though.

**Comment by stereobooster** [comment]
@zenntenn thanks https://marketplace.visualstudio.com/items?itemName=meraymond.idris-vscode

**Comment by IFcoltransG** [comment]
I did a search for `meraymond.idris-vscode` in Code, with many results containing the word 'vscode', all unrelated. I copied the command `ext install meraymond.idris-vscode` from the extension page and pasted it into the CTRL+P menu, which took me to the same search results. I ran `code --install-extension meraymond.idris-vscode` in the terminal with the following result:
```
Installing extensions...
Extension 'meraymond.idris-vscode' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: meraymond.idris-vscode
```
Something fishy is clearly going on.

For some context, `code --version`
```
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```
I'm using the Manjaro community version of `code` on the `5.10.7-arch1-1-g14` kernel.

**Comment by meraymond2** [comment]
Can you tell me which marketplace your installation of vscode is using? For example, I have both vscode and vscodium installed, and they're using `https://marketplace.visualstudio.com` and `https://open-vsx.org` respectively. I haven't published the extension to open-vsx yet. 

I haven't found this info in the UI, but if you look at `~/.config/Code/Network\ Persistent\ State`, one of the elements in net.http_server_properties.servers should look like a marketplace url. The vscode directory may have a different name for you, it's `Code` on this laptop which is running Mint, but when I used Arch it was something like `~/.config/Code - OSS/`

**Comment by IFcoltransG** [comment]
I have https://marketplace.visualstudio.com and https://open-vsx.org both listed.

**Comment by IFcoltransG** [comment]
As a workaround, I installed by downloading the .vsix file from the marketplace website, using `code --install-extension meraymond.idris-vscode-0.0.7.vsix` and restarting VS Code.

**Comment by meraymond2** [comment]
I've investigated publishing this to open-vsx.org but the process to create an Eclipse Foundation account was too invasive — I'm not prepared to give them my address :roll_eyes:

For now, my recommendation is to just download the vsix file from the Visual Studio marketplace and install it manually, if you're not able to download it from the Microsoft extension repo.
