### ISSUE TITLE
Support generate definition

### ISSUE THREAD

**Issue by michaelmesser** [meraymond2/idris-vscode#35]
Here is how generate definition is defined in [Idris 2's vim plugin](https://github.com/edwinb/idris2-vim/blob/964cebee493c85f75796e4f4e6bbb4ac54e2da9e/ftplugin/idris2.vim#L158-L171).

**Comment by meraymond2** [comment]
Cool, I didn't know about that command, I'll see about implementing it. I will also look at proof-search-next and generate-definition-next.

**Comment by meraymond2** [comment]
https://github.com/meraymond2/idris-vscode/pull/39
