### ISSUE TITLE
open-vsx support

### ISSUE THREAD

**Issue by Qeenon** [meraymond2/idris-vscode#43]
Please support https://open-vsx.org/
It's used for vscodium https://vscodium.com/

**Comment by meraymond2** [comment]
I'll see. The last time I looked at it, they required far too much personal information simply to create an account, but I'll see if I can get around that. 

In the meantime, you can download the vsix from the [MS marketplace](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/meraymond/vsextensions/idris-vscode/0.0.8/vspackage), and install it manually.

**Comment by meraymond2** [comment]
It's published

**Comment by Qeenon** [comment]
thank you
