### ISSUE TITLE
Syntax highlighting sometimes fails

### ISSUE THREAD

**Issue by Z-snails** [meraymond2/idris-vscode#46]
In some files syntax highlighting fails, even in a well defined file

For example
```
sendRequest : LinearIO io =>
       (1 _ : Socket Open) ->
       (msg : Request) ->
       L io {use=1} (Res Bool (\res => Socket (case res of
                                                    False => Closed
                                                    True => Open)))
sendRequest soc req = send soc (buildRequest req)
```
fails to highlight properly after the case expression.

Edit:
I believe this may be a problem with brackets in types where the start and end are on different lines, as when I replace the brackets with $s it highlights correctly.

**Comment by meraymond2** [comment]
I'm not 100% sure what you mean by 'fails to highlight properly after the case expression.', but I think I see it. The function_signature rule is matching a bit too much, and is overriding other more meaningful scopes. I think I can reduce it a bit, I'm pretty sure the only meaningful scope it adds is to the function-name itself.

Just to confirm, is this what you had in mind?
Monokai:
Before:
![image](https://user-images.githubusercontent.com/13559686/112757506-de9a4d80-8fe1-11eb-8fc8-c694107378d5.png)
After:
![image](https://user-images.githubusercontent.com/13559686/112757519-e9ed7900-8fe1-11eb-8e40-b157a72f8e71.png)

One Dark:
Before:
![image](https://user-images.githubusercontent.com/13559686/112757530-fbcf1c00-8fe1-11eb-934d-bc885c7ca5a9.png)
After:
![image](https://user-images.githubusercontent.com/13559686/112757543-12757300-8fe2-11eb-881c-614a6b2e38e2.png)

**Comment by Z-snails** [comment]
Yeah, that's what I meant. I mentioned the case expression to make it clear where the problem was (also initially I thought the case might have been the problem before I realised it was most likely the brackets).

Thanks for fixing it so quickly.

**Comment by meraymond2** [comment]
Just pushed a new version, with that change.
