### ISSUE TITLE
Failed to load file.

### ISSUE THREAD

**Issue by DUVELA** [meraymond2/idris-vscode#78]
sorry not Idris2.

Hi.
I was following the TDD idris book (10.3.3 TestStore.idr) in AMD fx8300 windows 10 visual studio code. However, I saw 'Failed to load file'. Is there any way? (In Atom and other extensions it works.)

**Comment by meraymond2** [comment]
Hi, apologies for taking so long to get back to you.

It could be a number of things, I'd need a reproducible example to know for sure. If you're still facing this issue, can you check the extension settings, and make sure `Idris2 Mode` isn't on?

**Comment by DUVELA** [comment]
Hi, My English level is so bad. I’m forgot this issue. 😃 Idris1 only (not install Idris2)C:\Users\i>idris --version1.3.3 Vscode idris extenstionIdris Language v0.0.12  I solved it like this:One is to use atoms.Another is to add it to C:\idris\libs\libs\base\TDD .(like ‘import Data.Vect’ TDD was use mkdir. ) Windows용 메일에서 발송된 메일입니다. 보낸 사람: meraymond2보낸 날짜: 2022년 3월 30일 수요일 오후 5:10받는 사람: meraymond2/idris-vscode참조: -; Author제목: Re: [meraymond2/idris-vscode] Failed to load file. (Issue #78) Hi, apologies for taking so long to get back to you.It could be a number of things, I'd need a reproducible example to know for sure. If you're still facing this issue, can you check the extension settings, and make sure Idris2 Mode isn't on?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
