### ISSUE TITLE
Having issue with extension 

### ISSUE THREAD

**Issue by MoonApache** [meraymond2/idris-vscode#90]
Hello, 
having this erorr on macOS: 

[error] Error: Illegal argument: line must be non-negative
	at v (/Applications/Visual Studio

**Comment by meraymond2** [comment]
Hi, did you find a solution to this problem? I have an idea of what might cause it but haven't had a chance to reproduce it yet.

**Comment by MoonApache** [comment]
I had found that when you open folder where is file it works , but if you open folder , where is folder with the file it cannot work

**Comment by funarog** [comment]
I am having issues how do I test?

**Comment by meraymond2** [comment]
Hey, are you having the same issue? `line must be non-negative`
